import { Platform, StatusBar, StyleSheet } from "react-native";
import { C } from "./types";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  menuContainer: { flex: 1, paddingHorizontal: 24, justifyContent: "space-between", paddingBottom: 24 },
  menuHeader: { alignItems: "center", paddingTop: 60 },
  menuTitle: { fontSize: 56, fontWeight: "900", color: C.text, letterSpacing: 8 },
  menuSubtitle: { fontSize: 14, fontWeight: "700", color: C.accent, letterSpacing: 4, marginTop: -4 },
  menuDivider: { width: 60, height: 2, backgroundColor: C.accent, borderRadius: 1, marginVertical: 16 },
  menuTagline: { fontSize: 14, color: C.muted },
  menuButtons: { gap: 12 },
  menuBtn: { backgroundColor: C.accent, borderRadius: 14, padding: 18, flexDirection: "row", alignItems: "center", gap: 14, borderWidth: 1, borderColor: C.accent },
  menuBtnDim: { backgroundColor: C.card, borderColor: C.border },
  menuBtnIcon: { fontSize: 22 },
  menuBtnText: { fontSize: 17, fontWeight: "700", color: C.text },
  menuBtnSub: { fontSize: 12, color: C.dim },
  version: { textAlign: "center", color: C.dim, fontSize: 12 },
  setupContainer: { padding: 20, paddingBottom: 48 },
  setupTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 28 },
  backBtn: { color: C.accent, fontSize: 15 },
  setupTitle: { fontSize: 18, fontWeight: "700", color: C.text },
  sectionLabel: { fontSize: 12, fontWeight: "700", color: C.muted, textTransform: "uppercase", letterSpacing: 1.2, marginBottom: 10 },
  gameTypeCard: { backgroundColor: C.card, borderRadius: 12, padding: 14, borderWidth: 2, borderColor: C.border, marginBottom: 10 },
  gameTypeCardActive: { borderColor: C.accent, backgroundColor: C.accentDim },
  gameTypeLabel: { fontSize: 15, fontWeight: "700", color: C.muted, marginBottom: 2 },
  gameTypeDesc: { fontSize: 12, color: C.dim },
  input: { backgroundColor: C.cardAlt, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, color: C.text, borderWidth: 1, borderColor: C.border, marginBottom: 12 },
  lifePickRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 24, marginBottom: 12 },
  lifePickBtn: { backgroundColor: C.card, borderRadius: 12, width: 48, height: 48, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.border },
  lifePickBtnText: { fontSize: 24, color: C.text, lineHeight: 28 },
  lifePickVal: { fontSize: 48, fontWeight: "900", color: C.text, minWidth: 80, textAlign: "center" },
  presetRow: { flexDirection: "row", gap: 10, justifyContent: "center", marginBottom: 4 },
  preset: { paddingHorizontal: 20, paddingVertical: 8, borderRadius: 20, backgroundColor: C.card, borderWidth: 1, borderColor: C.border },
  presetActive: { backgroundColor: C.accentDim, borderColor: C.accent },
  presetText: { color: C.muted, fontWeight: "600" },
  startBtn: { backgroundColor: C.accent, borderRadius: 14, paddingVertical: 18, alignItems: "center", marginTop: 20 },
  startBtnText: { fontSize: 17, fontWeight: "800", color: C.text },
  topBar: { backgroundColor: C.card, borderBottomWidth: 1, borderBottomColor: C.border, paddingHorizontal: 20, paddingTop: Platform.OS === "android" ? (StatusBar.currentHeight ?? 0) + 14 : 30, paddingBottom: 14 },
  topBarRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  topPlayerName: { fontSize: 16, fontWeight: "700", color: C.text },
  turnBadge: { backgroundColor: C.accentDim, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4, borderWidth: 1, borderColor: C.accent },
  turnBadgeText: { fontSize: 12, fontWeight: "700", color: C.accent },
  lifeBtnText: { fontSize: 22, color: C.text, lineHeight: 26, fontWeight: "300" },
  lifeVal: { fontSize: 48, fontWeight: "900", color: C.text, lineHeight: 54 },
  statsRow: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 16 },
  stat: { alignItems: "center" },
  statVal: { fontSize: 18, fontWeight: "800", color: C.text },
  statLabel: { fontSize: 10, color: C.muted, letterSpacing: 0.5, marginTop: 2 },
  statDiv: { width: 1, height: 28, backgroundColor: C.border },
  card: { backgroundColor: C.card, borderRadius: 14, borderWidth: 1, borderColor: C.border, overflow: "hidden" },
  sectionHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: C.border, backgroundColor: C.cardAlt },
  sectionTitle: { fontSize: 12, fontWeight: "700", color: C.muted, textTransform: "uppercase", letterSpacing: 1.2 },
  badge: { backgroundColor: C.accentDim, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 2 },
  badgeText: { fontSize: 11, fontWeight: "600", color: C.accent },
  dotRowContainer: { flexDirection: "row", gap: 4, flexWrap: "wrap", justifyContent: "center", paddingHorizontal: 14, paddingVertical: 12 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: C.border },
  dotActive: { backgroundColor: C.accent, width: 14, borderRadius: 3 },
  dotPast: { backgroundColor: C.dim },
  phaseName: { fontSize: 24, fontWeight: "900", color: C.text },
  phaseDesc: { fontSize: 13, color: C.muted, lineHeight: 18, paddingHorizontal: 14, marginTop: 4, marginBottom: 8 },
  phaseProgress: { fontSize: 11, color: C.dim, paddingHorizontal: 14, marginBottom: 14, textTransform: "uppercase", letterSpacing: 0.8 },
  bottomBar: { position: "absolute", bottom: 40, left: 0, right: 0, backgroundColor: "transparent", borderTopWidth: 1, borderTopColor: C.border, flexDirection: "row", alignItems: "center", paddingHorizontal: 12, paddingVertical: 10, paddingBottom: Platform.OS === "ios" ? 28 : 12, gap: 8 },
  bottomBarConfirm: { flex: 1, height: 52, borderRadius: 12, alignItems: "center", justifyContent: "center", borderWidth: 1 },
  bottomBarConfirmText: { fontSize: 15, fontWeight: "700", color: C.text },
  bottomBarHub: { width: 52, height: 52, borderRadius: 26, backgroundColor: C.accent, alignItems: "center", justifyContent: "center", elevation: 4 },
  bottomBarHubIcon: { fontSize: 22, color: C.text, fontWeight: "700" },
  confirmBtnOk: { backgroundColor: C.accentDim, borderColor: C.accent },
  confirmBtnUnlock: { backgroundColor: C.warningDim, borderColor: C.warning },
  confirmBtnWarn: { backgroundColor: C.dangerDim, borderColor: C.danger },
  confirmBtnText: { fontSize: 15, fontWeight: "700", color: C.text },
  reminderItem: { flexDirection: "row", alignItems: "flex-start", paddingHorizontal: 14, paddingVertical: 10, gap: 10, borderBottomWidth: 1, borderBottomColor: C.border },
  reminderTitle: { fontSize: 14, fontWeight: "600", color: C.text, lineHeight: 18 },
  reminderDesc: { fontSize: 12, color: C.muted, marginTop: 2, lineHeight: 16 },
  resolveBtn: { borderRadius: 7, paddingHorizontal: 10, paddingVertical: 5, backgroundColor: C.successDim, borderWidth: 1, borderColor: C.success },
  resolveBtnText: { fontSize: 12, fontWeight: "700", color: C.success },
  skipBtn: { borderRadius: 7, paddingHorizontal: 10, paddingVertical: 5, backgroundColor: C.cardAlt, borderWidth: 1, borderColor: C.border },
  skipBtnText: { fontSize: 12, fontWeight: "600", color: C.muted },
  eventGrid: { flexDirection: "row", flexWrap: "wrap", padding: 10, gap: 8 },
  eventBtn: { backgroundColor: C.cardAlt, borderRadius: 10, paddingVertical: 10, paddingHorizontal: 12, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.border, width: "23%", minWidth: 72, gap: 4 },
  eventIcon: { fontSize: 18, fontWeight: "700" },
  eventLabel: { fontSize: 10, fontWeight: "600", color: C.muted, textAlign: "center", lineHeight: 13 },
  spellGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
  spellTypeBtn: { backgroundColor: C.cardAlt, borderRadius: 10, padding: 12, borderWidth: 1, borderColor: C.border, alignItems: "center", width: "22%", minWidth: 70, gap: 4 },
  spellTypeBtnActive: { backgroundColor: C.accentDim, borderColor: C.accent },
  spellTypeIcon: { fontSize: 20 },
  spellTypeLabel: { fontSize: 11, fontWeight: "600", color: C.muted, textAlign: "center" },
  backdrop: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0, backgroundColor: C.overlay },
  sheet: { backgroundColor: C.card, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, paddingBottom: 40, borderTopWidth: 1, borderColor: C.border },
  handle: { width: 36, height: 4, backgroundColor: C.border, borderRadius: 2, alignSelf: "center", marginBottom: 16 },
  sheetTitle: { fontSize: 18, fontWeight: "800", color: C.text, marginBottom: 16 },
  centeredOverlay: { flex: 1, backgroundColor: C.overlay, justifyContent: "center", alignItems: "center", padding: 20 },
  centeredModal: { backgroundColor: C.card, borderRadius: 16, padding: 24, width: "100%", maxWidth: 400, borderWidth: 1, borderColor: C.border, alignItems: "center" },
  closeBtnWide: { backgroundColor: C.cardAlt, borderRadius: 10, paddingVertical: 12, paddingHorizontal: 20, borderWidth: 1, borderColor: C.border, alignItems: "center", width: "100%" },
  closeBtn: { backgroundColor: C.cardAlt, borderRadius: 10, paddingVertical: 12, borderWidth: 1, borderColor: C.border, alignItems: "center", width: "100%" },
  closeBtnText: { fontSize: 14, fontWeight: "600", color: C.muted },
  actionBtn: { borderRadius: 10, paddingVertical: 13, alignItems: "center", borderWidth: 1, width: "100%" },
  qtyRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 24, marginBottom: 20 },
  qtyBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: C.cardAlt, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.border },
  modalBtnRow: { flexDirection: "row", gap: 10, marginTop: 8 },
  modalCancelBtn: { backgroundColor: C.cardAlt, borderRadius: 10, paddingVertical: 13, paddingHorizontal: 20, borderWidth: 1, borderColor: C.border, alignItems: "center" },
  modalConfirmBtn: { flex: 1, backgroundColor: C.accent, borderRadius: 10, paddingVertical: 13, alignItems: "center" },
  hubGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 16 },
  hubItem: { backgroundColor: C.cardAlt, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: C.border, width: "48%", gap: 2 },
  manaRow: { flexDirection: "row", alignItems: "center", paddingVertical: 12, paddingHorizontal: 4, borderBottomWidth: 1, borderBottomColor: C.border },
  manaEmoji: { fontSize: 22, width: 32 },
  manaLabel: { fontSize: 15, fontWeight: "700", color: C.text, flex: 1 },
  manaTotal: { fontSize: 28, fontWeight: "900", color: C.text, minWidth: 44, textAlign: "center" },
  manaAutoLabel: { fontSize: 10, color: C.dim, textAlign: "center" },
  manaBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.cardAlt, borderWidth: 1, borderColor: C.border, alignItems: "center", justifyContent: "center", marginHorizontal: 4 },
  manaBtnText: { fontSize: 20, color: C.text, lineHeight: 24 },
  gyTabRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
  gyTab: { flex: 1, paddingVertical: 10, borderRadius: 10, alignItems: "center", borderWidth: 1 },
  gyTabActive: { backgroundColor: C.accentDim, borderColor: C.accent },
  gyTabInactive: { backgroundColor: C.cardAlt, borderColor: C.border },
  gyTabText: { fontSize: 13, fontWeight: "700", color: C.text },
  gyRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 14, paddingVertical: 12, gap: 10, borderBottomWidth: 1, borderBottomColor: C.border },
  tokenGySmallBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, backgroundColor: C.cardAlt, borderWidth: 1, borderColor: C.border },
  tokenGySmallBtnText: { fontSize: 11, fontWeight: "700", color: C.muted },
  phaseListCard: { backgroundColor: C.card, borderRadius: 14, borderWidth: 1, borderColor: C.border, marginBottom: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 16 },
});
